# Full URL to the pages
url: "https://vasyaod.github.io"

# Base path
basePath: "/my-trips"

# Caption of the site.
siteTitle: "Favorite Bike Tracks"

# Header of the site
siteDescription: "Collection of my favorite bike and walking tracks."

# Distance threshold (meters) for filtering
distanceThreshold: 20

# Time threshold (seconds) for splitting of tracks
timeThreshold: 600

