# Full URL to the pages
url: "https://vasyaod.github.io/my-trips"

# Base path
basePath: "/my-trips"

# Caption of the site.
siteTitle: "Favorite Bike Tracks"

# Header of the site
siteDescription: "Collection of my favorite bike and walking tracks."

